/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.lab26_guiplashpersistence.model;

import edu.ec.espe.util.FileManager;
import java.io.File;

/**
 *
 * @author JDIsmael
 */
public class inputData extends javax.swing.JFrame {

    final double gravity = -9.8;
    double angle;
    double velocity;
    double result;
    int id=0;
    
    
    public inputData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAngleTitle = new javax.swing.JLabel();
        lblVelocityTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtAngle = new javax.swing.JTextField();
        txtVelocity = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAngleTitle.setText("Angulo de inclinacion");

        lblVelocityTitle.setText("Velocidad inicial: ");

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblTitle.setText("Calculo  movimiento parabolico");

        txtAngle.setText("en radianes");
        txtAngle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAngleFocusGained(evt);
            }
        });

        txtVelocity.setText("m/s");
        txtVelocity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVelocityFocusGained(evt);
            }
        });

        lblResult.setText("La posicion final del proyectil es ---> ");

        btnCalculate.setText("Calcular");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAngleTitle)
                            .addComponent(lblVelocityTitle))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(btnCalculate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblResult)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTitle)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAngleTitle)
                            .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVelocityTitle)
                            .addComponent(txtVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnCalculate)))
                .addGap(44, 44, 44)
                .addComponent(lblResult)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        angle = Double.parseDouble(txtAngle.getText().trim());
        velocity = Double.parseDouble(txtVelocity.getText().trim());
        
        result = (Math.pow(velocity, 2)* Math.sin(2*angle))/(gravity);
        while (FileManager.readFile(new File("data.csv")) != -1){
            id++;
            System.out.println("pasa por aqui " + id);
        }
        FileManager.writeFile(new File("data.csv"), id+";"+angle + ";" + velocity + ";" + result+"\n");
        setField();
        lblResult.setText("La posicion final del proyectil con angulo "+ angle+ " y velocidad "+velocity+" es ---> " + result);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtAngleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAngleFocusGained
        txtAngle.setText("");
    }//GEN-LAST:event_txtAngleFocusGained

    private void txtVelocityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVelocityFocusGained
        txtVelocity.setText("");
    }//GEN-LAST:event_txtVelocityFocusGained

    private void setField(){
        txtAngle.setText("en radianes");
        txtVelocity.setText("m/s");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblAngleTitle;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVelocityTitle;
    private javax.swing.JTextField txtAngle;
    private javax.swing.JTextField txtVelocity;
    // End of variables declaration//GEN-END:variables
}
