/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.lab22.gui;

/**
 *
 * @author JDIsmael
 */
public class Message extends javax.swing.JFrame {

    /**
     * Creates new form Mesag
     */
    public Message() {
        initComponents();
        this.setTitle("Como me llamo");
        this.setBounds(100, 100, 300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGreeting = new javax.swing.JButton();
        jLblName = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnGreeting.setText("Greeting");
        jBtnGreeting.setToolTipText("Haga click aqui  para saludarle");
        jBtnGreeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGreetingActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 147, -1, -1));

        jLblName.setText("Texto aqui");
        jLblName.setToolTipText("Aqui se vera su nombre");
        getContentPane().add(jLblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 65, 197, 64));

        jTxtName.setText("Ingrese Nombre");
        jTxtName.setToolTipText("Aqui ingrese su Naombre y su Apellido");
        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });
        jTxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 21, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGreetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGreetingActionPerformed
        jLblName.setText("Hola "+jTxtName.getText());
    }//GEN-LAST:event_jBtnGreetingActionPerformed

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        //jLblName.setText("Hola "+jTxtName.getText());
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jTxtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNameKeyTyped
        /*jLblName.setText("Hola "+jTxtName.getText());
        if (jTxtName.getText().length() >= 10) 
            evt.consume();*/
    }//GEN-LAST:event_jTxtNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Message().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGreeting;
    private javax.swing.JLabel jLblName;
    private javax.swing.JTextField jTxtName;
    // End of variables declaration//GEN-END:variables
}
